services:
  outline:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - redis
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/outline
      REDIS_URL: redis://redis:6379
  redis:
    image: redis
    user: "redis:redis"
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: outline
    user: "postgres:postgres"
